### ISSUE TITLE
Host run | Python 3.8.10 | auto-scan [ERROR] __init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by ivang-coder** [lacework-dev/container-auto-scan#32]
Hi Team,  
**Issue**  
i'm experiencing an issue running auto-scan locally on a Host where `"auto-scan [ERROR] __init__() got an unexpected keyword argument 'allowed_methods'"` pops up  
**Steps to reproduce**  
```
sudo apt install python3
sudo ln -s /usr/bin/python3 /usr/bin/python
pip install laceworksdk
pip install requests
pip install tabulate
./auto_scan.py --account SOME_ORG --api-key SOME_API_KEY --api-secret SOME_SECRET --list-only
"auto-scan [ERROR] __init__() got an unexpected keyword argument 'allowed_methods'"
```
**Environment**  
Platform: Windows Subsystem Linux
OS: Ubuntu 20.04.4 LTS
Python 3.8.10

Can you point out what's potentially missing or misconfigured?

Cheers,

**Comment by alannix-lw** [comment]
Check your version of pip (`pip --version`) and see which version of python it's using.  I would have expected you to either need to install it with `apt install python3-pip` or with the [get-pip.py](https://pip.pypa.io/en/stable/installation/#get-pip-py) script.  You should see something like this:
```
# pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

The python3 package doesn't install pip on it's own, so you likely have a previous instance of it.

**Comment by ivang-coder** [comment]
Hi Alan, thank you for your response. Running the suggested command revealed the below:
```
# pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```
Just to confirm the state, I also did the following
```
# apt install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I think everything is looking ok from PIP perspective. I'm considering running a docker to eliminate this issue, however it would be great to find the root cause for host-based run.

**Comment by alannix-lw** [comment]
Interesting, ok - can you also send me the output of `pip list`?  The urllib3 module is where the allowed_methods parameter is used (via requests).  That parameter was introduced in [1.26.0](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#1260-2020-11-10) of urllib3 so I may just need to explicitly ask for urllib3>=1.26.

**Comment by ivang-coder** [comment]
Hi Alan, yep, you're right **urllib3 is 1.25.8**. After running `"pip install urllib3 --upgrade"`, I got `urllib3-1.26.10`.  

Having attempted to run auto-scan, I got `"/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (3.0.4) doesn't match a supported version!"`  

After running `"pip install chardet --upgrade"`, I got `chardet-5.0.0`  

The attempt to run failed with `"/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (5.0.0) doesn't match a supported version!"`

Any ideas why the script doesn't like the up-to-date urllib3 and chardet?

**Comment by ivang-coder** [comment]
Hi Alan,
Having run `"pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U"`, I believe all the issues are now resolved and auto-scan runs with no error or warning messages.

Maybe you guys could include the list of commands below as requirements or prerequisites. I think it would be useful for newbies as well as seasoned operators.

**Prerequisites**
```
sudo apt update && sudo apt upgrade
sudo apt install python3 && sudo ln -s /usr/bin/python3 /usr/bin/python
pip install laceworksdk
pip install requests
pip install tabulate
pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U 
```
The ticket can be closed now, thank you.
