### ISSUE TITLE
containerd support?

### ISSUE THREAD

**Issue by albertrdixon** [lacework-dev/container-auto-scan#41]
We run this as a service in our Kubernetes clusters. With the removal of docker in kubernetes 1.24+, docker is no longer installed on our worker nodes. Could this project support and utilize the containerd socket if mounted instead of the docker socket?

**Comment by alannix-lw** [comment]
Thanks for the feedback @albertrdixon! Currently this project is effectively a scan federation utility.  This means, it will enumerate the active containers seen in a Lacework account, and then issue scan requests to Lacework's scanning utilities - Platform, Proxy, or Inline - based on the supplied arguments.  In the case of the Docker/containerd socket, that is used for Inline Scanner requests, and currently that scanner requires Docker to be installed.

If you'd like, you can [open a support ticket/feature request](https://support.lacework.com) to have containerd support added to the Inline Scanner.  Once the Inline Scanner supports containerd, it should be trivial for this project to inherit those capabilities.
